---
layout: post
title: "Hadoop集群搭建过程中的问题"
description: "我的情况是 datanode2启动失败，查询日志发现：
              org.apache.hadoop.hdfs.server.datanode.DataNode: Invalid directory in dfs.data.dir: /data/3/dfs/dn"
category: 技术
tags: [hadoop]
---
{% include JB/setup %}

## 某一个Datanode启动失败

我的情况是 datanode2启动失败，查询日志发现：   
org.apache.hadoop.hdfs.server.datanode.DataNode: Invalid directory in dfs.data.dir: /data/3/dfs/dn   

这是因为/data/3/dfs/ 这个目录的权限不对，要设置成755 并且用户和组都是 hdfs 解决：   
`chmod -R 755 /data/3/dfs/`   
`chown -R hdfs:hdfs /data/3/dfs/`

## Hbase 某一个节点启动失败

org.apache.hadoop.hbase.ClockOutOfSyncException: Server hadoop2.qct.b2.internal.chinacloudapp.cn,60020,1423151399371 ha
s been rejected; Reported time is too far out of sync with master.  Time difference of 60020ms > max allowed of 30000ms

是因为这个节点和其他节点时间差太多了，做了时间同步，重新启动OK。